version: "3.9"
services:
  redis:
    image: "redislabs/redismod:edge"
    ports:
      - "6379:6379"
    volumes:
      - ./data:/data
    entrypoint: >
      redis-server
        --loadmodule /usr/lib/redis/modules/redisai.so
          ONNX redisai_onnxruntime/redisai_onnxruntime.so
          TF redisai_tensorflow/redisai_tensorflow.so
          TFLITE redisai_tflite/redisai_tflite.so
          TORCH redisai_torch/redisai_torch.so
        --save 60 1
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
